### PR TITLE
add analysis notebook

### PR DESCRIPTION
**Pull request by Qi77Qi**

### CODE REVIEW

**Comment by rtitle** [comment]
Can we add IGV to this? 😁

**Comment by Qi77Qi** [comment]
@rtitle yea, definitely, I PRed this one yesterday since I thought we need to demo sth today...for adding IGV, do you have sth already? or I can ask Alessandro about it and add it to the PR (or a separate PR)

**Comment by rtitle** [comment]
Yeah I have some working code… hm would it work if I just add a commit to this branch?

**Comment by Qi77Qi** [comment]
yea, that'd be great! thanks!

**Comment by nmalfroy** [comment]
Also, feel free to merge into main as you go (this repo is pretty open and we're working on different files)

**Comment by rtitle** [comment]
I'm just gonna merge this I think

**Pull request merged**
